
// GET ALL BANNERS
export const ALL_BANNER_REQUEST = "ALL_BANNER_REQUEST";
export const ALL_BANNER_SUCCESS = "ALL_BANNER_SUCCESS";
export const ALL_BANNER_FAIL = "ALL_BANNER_FAIL";



// GET ALL BANNERS -ADMIN
export const ALL_ADMIN_BANNER_REQUEST = "ALL_ADMIN_BANNER_REQUEST";
export const ALL_ADMIN_BANNER_SUCCESS = "ALL_ADMIN_BANNER_SUCCESS";
export const ALL_ADMIN_BANNER_FAIL = "ALL_ADMIN_BANNER_FAIL";


// CREATE BANNER
export const NEW_BANNER_SUCCESS = "NEW_BANNER_SUCCESS";
export const NEW_BANNER_REQUEST = "NEW_BANNER_REQUEST";
export const NEW_BANNER_REST = "NEW_BANNER_REST"
export const NEW_BANNER_FAIL = "NEW_BANNER_FAIL";


// DELTE BANNER
export const DELETE_BANNNER_SUCCESS = "DELETE_BANNNER_SUCCESS";
export const DELETE_BANNNER_REQUEST = "DELETE_BANNNER_REQUEST";
export const DELETE_BANNNER_REST = "DELETE_BANNNER_REST"
export const DELETE_BANNNER_FAIL = "DELETE_BANNNER_FAIL";


export const CLEAR_ERRORS = "CLEAR_ERRORS"